/* eslint-disable prettier/prettier */
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  card_container: {
    borderRadius: 10,
    margin: 10,
    // backgroundColor: 'white',
    width: 150,
  },
  card: {
    borderRadius: 10,
    width: 150,
    height: 200,
  },
  card_title: {
    fontWeight: '600',
  },
  card_releasedate: {
    color: 'grey',
  },
  rating: {
    top: 175.5,
    left: 107.5,
    padding: 3,
    flexDirection: 'row',
    position: 'absolute',
    borderRadius: 10,
    // backgroundColor: '#3066bc',
  },
  rating_text: {
    fontSize: 12,
    marginLeft: 3,
    color: 'white',
  },
  buttons: {
    top: 400,
    flexDirection: 'row',
    position: 'absolute',
    marginRight: 50,
    justifyContent: 'space-around',
  },
  exitbutton: {
    top: 10,
    left: 380,
    position: 'absolute',
    borderRadius: 50,
  },
  download: {
    top: 140,
    left: 280,
    position: 'absolute',
    backgroundColor: '#3066bc',
    borderRadius: 50,
    height: 50,
    width: 50,
    paddingLeft: 15,
    paddingTop: 14,
  },
  playbutton: {
    top: 140,
    left: 200,
    position: 'absolute',
    backgroundColor: '#3066bc',
    borderRadius: 50,
    height: 50,
    width: 50,
    paddingLeft: 19,
    paddingTop: 14,
  },
  modal_container: {
    flex: 1,
  },
  bg_details: {
    position: 'absolute',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    bottom: 400,
    width: 412,
    height: 300,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    // top: 20,
    width: 412,
    height: 700,
    margin: 20,
    backgroundColor: 'black',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    margin: 10,
    borderRadius: 20,
    elevation: 2,
  },
  addfavorite: {
    bottom: 70,
    backgroundColor: '#3066bc',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalTitle: {
    // top: 10,
    fontWeight: 'bold',
    fontSize: 20,
    textAlign: 'center',
  },
  overview: {
    // height: 40,
    // flex: 1,
    margin: 5,
    textAlign: 'justify',
    // backgroundColor: 'white',
    // bottom: 80,
  },
  details: {
    top: 100,
  },
  details_text: {
    // backgroundColor:'white',
    marginVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginHorizontal: 10,
  },
  title_details: {
    // textAlign: 'center',
    marginHorizontal: 10,
    fontWeight: '600',
    fontSize: 12,
  },
  text_details: {
    fontSize: 10,
    marginHorizontal: 10,
  },
});
